spring:
  datasource:
    url: jdbc:mysql://localhost:3306/net_duty_sys?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml